export const LOGIN_ACTION = "[actions] login user";
export const REGISTER_ACTION = "[actions] register user";
export const SET_USER_TOKEN_MUTATION = "[mutations] set user token";
export const LOADING_SPINNER_MUTATION = "[mutations] loading spinner";
export const GET_USER_TOKEN_MUTATION = "[mutations] get user token";
export const GET_USER_TOKEN_GETTER = "[getter] auth user token";
export const GET_USER_DATA_ACTION = "[action] get user data";
export const LOGOUT_ACTION = "[action] logout user";
export const REMOVE_USER_DATA_TOKEN = "[mutation] remove user token data";
